import { evaluateEligibility } from "@/engine/eligibility";
import { ingestDocument } from "@/engine/documents";
import { consistencyChecks, routeHitl } from "@/engine/intelligence";
import type { Fact } from "@/engine/types";
import { NFST, NOS, POST_MATRIC, PRE_MATRIC, TOP_CLASS, schemeByCode } from "@/schemes/registry";
import { handleInbound, queueApplicantAlert } from "./bot";
import type { ApplicationRecord, Database, UserRecord } from "./models";

function facts(entries: Record<string, string | number | boolean | null>, source: Fact["source"] = "APPLICANT"): Fact[] {
  return Object.entries(entries).map(([field, value]) => ({
    field,
    value,
    source,
    confidence: source === "OCR" ? 0.76 : 0.99,
    verified: source !== "OCR",
  }));
}

function app(partial: Omit<ApplicationRecord, "eligibility" | "hitlLevel" | "hitlReasons" | "timeline" | "deficiencies" | "createdAt" | "updatedAt" | "documents"> & { documents?: ApplicationRecord["documents"]; status: ApplicationRecord["status"] }): ApplicationRecord {
  const scheme = schemeByCode(partial.schemeCode);
  const documents = partial.documents ?? [];
  const eligibility = evaluateEligibility(scheme, partial.facts);
  const findings = consistencyChecks(partial.facts, documents);
  const ocrFloor = documents.length ? Math.min(...documents.map((d) => d.ocrConfidence)) : 1;
  const institutionPending =
    scheme.workflow.includes("INSTITUTION_VERIFICATION") &&
    partial.facts.find((f) => f.field === "institutionVerified")?.value !== true &&
    partial.status === "INSTITUTION_VERIFICATION";
  const hitl = routeHitl({
    ocrFloor,
    findings,
    missingEvidence: eligibility.outcome === "DEFICIENT",
    institutionPending,
    policyException: eligibility.outcome === "REVIEW_REQUIRED",
  });
  const now = "2026-09-10T09:00:00.000Z";
  return {
    ...partial,
    documents,
    eligibility,
    hitlLevel: hitl.level,
    hitlReasons: hitl.reasons,
    deficiencies:
      eligibility.outcome === "DEFICIENT"
        ? [
            {
              id: `def-${partial.id}`,
              applicationId: partial.id,
              reason: eligibility.traces.filter((t) => !t.passed).map((t) => t.description).join("; "),
              status: "OPEN",
              createdAt: now,
            },
          ]
        : [],
    timeline: [
      { at: now, stage: "SUBMITTED", note: "Application submitted", actor: partial.applicantName },
      { at: now, stage: partial.status, note: "Current stage", actor: "system" },
    ],
    createdAt: now,
    updatedAt: now,
  };
}

const users: UserRecord[] = [
  { id: "u-app", name: "Meena Xaxa", email: "applicant@mota.demo", role: "APPLICANT", password: "demo", mobile: "9876543210", lang: "hi" },
  { id: "u-app2", name: "Birsa Munda", email: "birsa@mota.demo", role: "APPLICANT", password: "demo", mobile: "9123456780", lang: "en" },
  { id: "u-ino", name: "Dr. Ananya Rao (IIT Delhi INO)", email: "ino@mota.demo", role: "INO", password: "demo", institutionId: "IITD" },
  { id: "u-state", name: "Jharkhand State Nodal Officer", email: "state@mota.demo", role: "STATE", password: "demo", stateCode: "JH" },
  { id: "u-mota", name: "MoTA Verification Officer", email: "officer@mota.demo", role: "MOTA", password: "demo" },
  { id: "u-comm", name: "NOS Expert Committee", email: "committee@mota.demo", role: "COMMITTEE", password: "demo" },
  { id: "u-fin", name: "Finance / PFMS boundary", email: "finance@mota.demo", role: "FINANCE", password: "demo" },
  { id: "u-admin", name: "Scheme Administrator", email: "admin@mota.demo", role: "ADMIN", password: "demo" },
  { id: "u-aud", name: "Auditor", email: "auditor@mota.demo", role: "AUDITOR", password: "demo" },
];

export function seedDatabase(): Database {
  const nfstCleanDocs = [
    ingestDocument({ applicationId: "NFST-2026-0001", documentType: "ST_CERTIFICATE", fileName: "st-meena.pdf" }),
    ingestDocument({ applicationId: "NFST-2026-0001", documentType: "MARKSHEET", fileName: "pg-meena.pdf" }),
    ingestDocument({ applicationId: "NFST-2026-0001", documentType: "ADMISSION_LETTER", fileName: "iitd-phd.pdf" }),
  ];
  const nfstOcrDocs = [
    ingestDocument({
      applicationId: "NFST-2026-0002",
      documentType: "ST_CERTIFICATE",
      fileName: "st-blurry.pdf",
      ocrConfidence: 0.72,
      extractedOverride: { fullName: "Mina Xaxa", stStatus: true, domicileState: "JH" },
    }),
    ingestDocument({ applicationId: "NFST-2026-0002", documentType: "MARKSHEET", fileName: "pg.pdf", ocrConfidence: 0.74, extractedOverride: { fullName: "Mina Xaxa", mastersPercentage: 81.4 } }),
  ];
  const nfstConflictDocs = [
    ingestDocument({
      applicationId: "NFST-2026-0003",
      documentType: "ST_CERTIFICATE",
      fileName: "st.pdf",
      extractedOverride: { fullName: "Somai Paharia", stStatus: true },
    }),
    ingestDocument({
      applicationId: "NFST-2026-0003",
      documentType: "INCOME_CERTIFICATE",
      fileName: "income.pdf",
      extractedOverride: { fullName: "S. Pahria", familyIncome: 240000 },
    }),
  ];

  const applications: ApplicationRecord[] = [
    app({
      id: "NFST-2026-0001",
      schemeCode: NFST.code,
      schemeVersion: NFST.version,
      academicYear: NFST.academicYear,
      applicantId: "u-app",
      applicantName: "Meena Xaxa",
      institutionName: "IIT Delhi",
      stateCode: "JH",
      status: "MOTA_SCRUTINY",
      documents: nfstCleanDocs,
      facts: facts({
        fullName: "Meena Xaxa",
        gender: "FEMALE",
        stStatus: true,
        domicileState: "JH",
        pvtg: false,
        divyangjan: false,
        bankAccount: true,
        aadhaarLinked: true,
        otherScholarship: false,
        ageOn1July: 28,
        mastersPercentage: 82.4,
        phdProgramme: true,
        institutionEligible: true,
        institutionVerified: true,
        premierOfferIitIimIiserAiims: true,
        researchDiscipline: "Computer Science",
        freshOrRenewal: "FRESH",
      }),
    }),
    app({
      id: "NFST-2026-0002",
      schemeCode: NFST.code,
      schemeVersion: NFST.version,
      academicYear: NFST.academicYear,
      applicantId: "u-app",
      applicantName: "Meena Xaxa",
      institutionName: "IIT Delhi",
      stateCode: "JH",
      status: "MOTA_SCRUTINY",
      documents: nfstOcrDocs,
      facts: facts({
        fullName: "Meena Xaxa",
        gender: "FEMALE",
        stStatus: true,
        domicileState: "JH",
        pvtg: false,
        divyangjan: false,
        bankAccount: true,
        aadhaarLinked: true,
        otherScholarship: false,
        ageOn1July: 28,
        mastersPercentage: 81.4,
        phdProgramme: true,
        institutionEligible: true,
        institutionVerified: true,
        premierOfferIitIimIiserAiims: true,
        researchDiscipline: "Computer Science",
        freshOrRenewal: "FRESH",
      }, "OCR"),
    }),
    app({
      id: "NFST-2026-0003",
      schemeCode: NFST.code,
      schemeVersion: NFST.version,
      academicYear: NFST.academicYear,
      applicantId: "u-app2",
      applicantName: "Somai Paharia",
      institutionName: "Ranchi University",
      stateCode: "JH",
      status: "MOTA_SCRUTINY",
      documents: nfstConflictDocs,
      facts: facts({
        fullName: "Somai Paharia",
        gender: "MALE",
        stStatus: true,
        domicileState: "JH",
        pvtg: true,
        divyangjan: false,
        bankAccount: true,
        aadhaarLinked: true,
        otherScholarship: false,
        ageOn1July: 31,
        mastersPercentage: 67.0,
        phdProgramme: true,
        institutionEligible: true,
        institutionVerified: true,
        premierOfferIitIimIiserAiims: false,
        researchDiscipline: "Anthropology",
        freshOrRenewal: "FRESH",
      }),
    }),
    app({
      id: "NFST-2026-0004",
      schemeCode: NFST.code,
      schemeVersion: NFST.version,
      academicYear: NFST.academicYear,
      applicantId: "u-app2",
      applicantName: "Lalita Ho",
      institutionName: "JNU",
      stateCode: "JH",
      status: "INSTITUTION_VERIFICATION",
      facts: facts({
        fullName: "Lalita Ho",
        gender: "FEMALE",
        stStatus: true,
        domicileState: "JH",
        pvtg: false,
        divyangjan: true,
        bankAccount: true,
        aadhaarLinked: true,
        otherScholarship: false,
        ageOn1July: 29,
        mastersPercentage: 78.2,
        phdProgramme: true,
        institutionEligible: true,
        institutionVerified: false,
        premierOfferIitIimIiserAiims: false,
        researchDiscipline: "Political Science",
        freshOrRenewal: "FRESH",
      }),
    }),
    app({
      id: "NFST-2026-0005",
      schemeCode: NFST.code,
      schemeVersion: NFST.version,
      academicYear: NFST.academicYear,
      applicantId: "u-app2",
      applicantName: "Ratan Bhil",
      institutionName: "MSU Baroda",
      stateCode: "GJ",
      status: "ELIGIBILITY",
      facts: facts({
        fullName: "Ratan Bhil",
        gender: "MALE",
        stStatus: true,
        domicileState: "GJ",
        pvtg: false,
        divyangjan: false,
        bankAccount: true,
        aadhaarLinked: true,
        otherScholarship: false,
        ageOn1July: 40,
        mastersPercentage: 71,
        phdProgramme: true,
        institutionEligible: true,
        institutionVerified: true,
        premierOfferIitIimIiserAiims: false,
        researchDiscipline: "History",
        freshOrRenewal: "FRESH",
      }),
    }),
    app({
      id: "NOS-2026-0001",
      schemeCode: NOS.code,
      schemeVersion: NOS.version,
      academicYear: NOS.academicYear,
      applicantId: "u-app",
      applicantName: "Meena Xaxa",
      stateCode: "JH",
      status: "COMMITTEE",
      facts: facts({
        fullName: "Meena Xaxa",
        gender: "FEMALE",
        stStatus: true,
        domicileState: "JH",
        pvtg: false,
        divyangjan: false,
        orphanStatus: false,
        familyIncome: 420000,
        bankAccount: true,
        aadhaarLinked: true,
        otherScholarship: false,
        programmeLevel: "PHD",
        ageOn1July: 28,
        qualifyingMarks: 82.4,
        qsWorldRank: 45,
        fieldOfStudy: "STEM",
        foreignInstitution: "University of Cambridge",
        admissionStatus: "OFFER",
        oneChildDeclaration: true,
        previousNos: false,
        proposal: "Climate-resilient agriculture sensing for eastern India plateau.",
      }),
    }),
    app({
      id: "NOS-2026-0002",
      schemeCode: NOS.code,
      schemeVersion: NOS.version,
      academicYear: NOS.academicYear,
      applicantId: "u-app2",
      applicantName: "Jamuna Korwa",
      stateCode: "CG",
      status: "ELIGIBILITY",
      facts: facts({
        fullName: "Jamuna Korwa",
        gender: "FEMALE",
        stStatus: true,
        domicileState: "CG",
        pvtg: true,
        familyIncome: 810000,
        bankAccount: true,
        aadhaarLinked: true,
        otherScholarship: false,
        programmeLevel: "MASTERS",
        ageOn1July: 24,
        qualifyingMarks: 68,
        fieldOfStudy: "HUM",
        foreignInstitution: "SOAS",
        admissionStatus: "SEEKING",
        oneChildDeclaration: true,
        previousNos: false,
        proposal: "Oral histories of PVTG communities.",
      }),
    }),
    app({
      id: "PRE-2026-0001",
      schemeCode: PRE_MATRIC.code,
      schemeVersion: PRE_MATRIC.version,
      academicYear: PRE_MATRIC.academicYear,
      applicantId: "u-app2",
      applicantName: "Suman Oraon",
      stateCode: "JH",
      status: "STATE_VERIFICATION",
      facts: facts({
        fullName: "Suman Oraon",
        gender: "FEMALE",
        stStatus: true,
        domicileState: "JH",
        familyIncome: 180000,
        orphanStatus: false,
        bankAccount: true,
        aadhaarLinked: true,
        otherScholarship: false,
        classLevel: "IX",
        schoolRecognised: true,
        hosteller: true,
        repeatClass: false,
        freshOrRenewal: "FRESH",
        divyangjan: false,
      }),
    }),
    app({
      id: "PMS-2026-0001",
      schemeCode: POST_MATRIC.code,
      schemeVersion: POST_MATRIC.version,
      academicYear: POST_MATRIC.academicYear,
      applicantId: "u-app2",
      applicantName: "Birsa Munda",
      institutionName: "IIT Delhi",
      stateCode: "JH",
      status: "ELIGIBILITY",
      facts: facts({
        fullName: "Birsa Munda",
        gender: "MALE",
        stStatus: true,
        domicileState: "JH",
        familyIncome: 210000,
        bankAccount: true,
        aadhaarLinked: true,
        otherScholarship: false,
        previousQualification: "Class XII",
        course: "B.Tech",
        courseGroup: "I",
        institutionRecognised: true,
        institutionInTopClassList: true,
        hosteller: true,
        feeAmount: 180000,
        freshOrRenewal: "FRESH",
      }),
    }),
    app({
      id: "TC-2026-0001",
      schemeCode: TOP_CLASS.code,
      schemeVersion: TOP_CLASS.version,
      academicYear: TOP_CLASS.academicYear,
      applicantId: "u-app2",
      applicantName: "Birsa Munda",
      institutionName: "IIT Delhi",
      stateCode: "JH",
      status: "INSTITUTION_VERIFICATION",
      facts: facts({
        fullName: "Birsa Munda",
        gender: "MALE",
        stStatus: true,
        domicileState: "JH",
        familyIncome: 210000,
        bankAccount: true,
        aadhaarLinked: true,
        otherScholarship: false,
        institutionInTopClassList: true,
        course: "B.Tech Computer Science",
        admittedOnMerit: true,
        freshOrRenewal: "FRESH",
        married: false,
      }),
    }),
    ...[
      { id: "NFST-2026-0006", name: "Phoolmani Kharia", gender: "FEMALE" as const, pvtg: false, divyangjan: true, marks: 88.1, premier: false, state: "OD", status: "SELECTION" as const },
      { id: "NFST-2026-0007", name: "Sukru Baiga", gender: "MALE" as const, pvtg: true, divyangjan: false, marks: 74.2, premier: false, state: "MP", status: "SELECTION" as const },
      { id: "NFST-2026-0008", name: "Anita Garo", gender: "FEMALE" as const, pvtg: false, divyangjan: false, marks: 91.0, premier: true, state: "AS", status: "AWARDED" as const },
      { id: "NFST-2026-0009", name: "David Hmar", gender: "MALE" as const, pvtg: false, divyangjan: false, marks: 79.5, premier: false, state: "MZ", status: "AWARDED" as const },
      { id: "NFST-2026-0010", name: "Mary Wangkhem", gender: "FEMALE" as const, pvtg: false, divyangjan: false, marks: 69.8, premier: false, state: "MN", status: "SELECTION" as const },
      { id: "NFST-2026-0011", name: "Raju Rathwa", gender: "MALE" as const, pvtg: false, divyangjan: true, marks: 63.4, premier: false, state: "GJ", status: "SELECTION" as const },
      { id: "NFST-2026-0012", name: "Sita Korwa", gender: "FEMALE" as const, pvtg: true, divyangjan: false, marks: 85.6, premier: false, state: "CG", status: "SELECTION" as const },
    ].map((row) =>
      app({
        id: row.id,
        schemeCode: NFST.code,
        schemeVersion: NFST.version,
        academicYear: NFST.academicYear,
        applicantId: "u-app2",
        applicantName: row.name,
        institutionName: row.premier ? "IIM Ahmedabad" : "Central University",
        stateCode: row.state,
        status: row.status,
        facts: facts({
          fullName: row.name,
          gender: row.gender,
          stStatus: true,
          domicileState: row.state,
          pvtg: row.pvtg,
          divyangjan: row.divyangjan,
          bankAccount: true,
          aadhaarLinked: true,
          otherScholarship: false,
          ageOn1July: 27,
          mastersPercentage: row.marks,
          phdProgramme: true,
          institutionEligible: true,
          institutionVerified: true,
          premierOfferIitIimIiserAiims: row.premier,
          researchDiscipline: "Social Sciences",
          freshOrRenewal: "FRESH",
        }),
      }),
    ),
  ];

  const db: Database = {
    users,
    applications,
    notifications: [
      {
        id: "n1",
        userId: "u-app",
        title: "NFST-2026-0001 is in MoTA scrutiny",
        body: "Institution verification is complete. An authorised officer still has to confirm the decision.",
        at: "2026-09-12T08:00:00.000Z",
        read: false,
      },
      {
        id: "n2",
        userId: "u-ino",
        title: "45% NFST backlog pattern",
        body: "NFST-2026-0004 is still waiting on institution verification. Late 2025 MoTA notices flagged this as the main delay.",
        at: "2026-09-12T08:05:00.000Z",
        read: false,
      },
    ],
    audit: [
      {
        id: "a1",
        at: "2026-09-10T09:00:00.000Z",
        actorId: "system",
        actorName: "Scheme engine",
        action: "SEED",
        detail: "Loaded five published scheme versions with source-document citations.",
      },
    ],
    awards: [
      {
        id: "awd-NFST-2026-0008",
        applicationId: "NFST-2026-0008",
        schemeCode: "NFST",
        status: "PAID",
        lifecycle: "ACTIVE",
        components: [
          "₹37,000/month JRF equivalent for first two years (portal, w.e.f. 1 Jan 2023)",
          "₹42,000/month thereafter for remaining three years",
        ],
        milestones: [
          { id: "m-join", label: "Joining / acceptance confirmed by applicant", status: "DONE", at: "2026-08-20T09:00:00.000Z" },
          { id: "m-inst", label: "Institution / programme confirmation on record", status: "DONE", at: "2026-08-22T09:00:00.000Z" },
          { id: "m-disb", label: "First disbursement acknowledged", status: "DONE", at: "2026-08-28T09:00:00.000Z" },
        ],
        createdAt: "2026-08-15T09:00:00.000Z",
        joinedAt: "2026-08-20T09:00:00.000Z",
      },
      {
        id: "awd-NFST-2026-0009",
        applicationId: "NFST-2026-0009",
        schemeCode: "NFST",
        status: "SANCTIONED",
        lifecycle: "AWARDED",
        components: [
          "₹37,000/month JRF equivalent for first two years (portal, w.e.f. 1 Jan 2023)",
          "₹42,000/month thereafter for remaining three years",
        ],
        milestones: [
          { id: "m-join", label: "Joining / acceptance confirmed by applicant", status: "PENDING" },
          { id: "m-inst", label: "Institution / programme confirmation on record", status: "PENDING" },
          { id: "m-disb", label: "First disbursement acknowledged", status: "PENDING" },
        ],
        createdAt: "2026-09-10T09:00:00.000Z",
      },
    ],
    selectionRuns: [],
    renewals: [],
    aiFeedback: [
      {
        id: "fb1",
        applicationId: "NFST-2026-0002",
        field: "fullName",
        predictedValue: "Mina Xaxa",
        correctedValue: "Meena Xaxa",
        officerId: "u-mota",
        officerName: "MoTA Verification Officer",
        reason: "OCR misread the ST certificate; application form and marksheet agree.",
        modelVersion: "field-extractor-v1.8",
        at: "2026-09-11T10:00:00.000Z",
      },
    ],
    policyStatus: {
      PRE_MATRIC: "PUBLISHED",
      POST_MATRIC: "PUBLISHED",
      TOP_CLASS: "PUBLISHED",
      NFST: "PUBLISHED",
      NOS: "PUBLISHED",
    },
    outbox: [],
  };

  // Demo WhatsApp history for Meena (Hindi): a proactive alert, then a status query.
  const meena = db.users.find((u) => u.id === "u-app")!;
  const note = db.notifications.find((n) => n.userId === "u-app");
  if (note) queueApplicantAlert(db, meena, note.title, note.body);
  handleInbound(db, meena.mobile!, "STATUS", "WHATSAPP");
  db.outbox.forEach((m, i) => {
    m.at = new Date(Date.parse("2026-09-12T08:00:00.000Z") + (db.outbox.length - i) * 60_000).toISOString();
  });
  return db;
}
